# -*- coding: utf-8 -*-
"""pythoncontrolprueba2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19iDyq9A1jSzGcUo_yHygOVvdu-24K5R_

# **ESTABILIDAD**
"""

# Commented out IPython magic to ensure Python compatibility.
#1.Standard Python libraries:
import math
import random
import time

#2.Third-party libraries:
import numpy as np
import control
import ipywidgets as widgets
# %matplotlib ipympl
import matplotlib.pyplot as plt
import matplotlib.path as mpath
import sympy

#3.Specific modules from third-party libraries:
from scipy import signal
from scipy.integrate.quadpack import tplquad
from scipy.signal.windows.windows import kaiser

from tbcontrol.symbolic import routh

from sympy import *
from IPython import display

from google.colab import output
output.enable_custom_widget_manager()

def funcionplotea():
  fig = plt.figure(figsize = (5,5))
  ax = fig.add_subplot(1,1,1)
  ax.plot([0,1],[0,1])
